"""
Validation harness: does the weekly variance model match reality?

Every probability this app prints — win probability, playoff odds, swing, start/sit, the margin
curve — is generated by drawing weekly scores around a projection with a spread set by WEEK_CV.
Those numbers had never been checked against actual weekly scoring. The 85 self-tests verify the
model is CONSISTENT; nothing verified it was RIGHT, and a coherent wrong model passes all of them.

Measured here, out of sample, from nflverse weekly player stats:
  1. the coefficient of variation of real weekly fantasy scoring, by position
  2. the SHAPE of that distribution (skew), which is the justification for using a lognormal
  3. the 15th/50th/85th percentile of week/mean, which is what the floor-ceiling bands claim

A player is only counted once he has 8+ games in a season, and each player is measured against HIS
OWN season mean, so this is week-to-week noise around a known level — exactly the quantity the
simulator draws — and not the much larger error of forecasting the level itself.
"""
import urllib.request, csv, io, json, os, math, statistics as st, collections

HERE=os.path.dirname(os.path.abspath(__file__))
SEASONS=(2021,2022,2023,2024)
URL="https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_{}.csv"
POS=("QB","RB","WR","TE")

def get(u):
    r=urllib.request.Request(u,headers={"User-Agent":"Mozilla/5.0"})
    return urllib.request.urlopen(r,timeout=240).read().decode("utf8","replace")

series=collections.defaultdict(list)      # (player,season,pos) -> [weekly ppr]
for yr in SEASONS:
    try: raw=get(URL.format(yr))
    except Exception as ex:
        print(f"  {yr}: fetch failed {ex}"); continue
    rd=csv.DictReader(io.StringIO(raw))
    n=0
    for r in rd:
        if (r.get("season_type") or "REG")!="REG": continue
        pos=r.get("position")
        if pos not in POS: continue
        v=r.get("fantasy_points_ppr")
        if v in (None,""): continue
        try: v=float(v)
        except Exception: continue
        series[(r.get("player_id"),yr,pos)].append(v)
        n+=1
    print(f"  {yr}: {n:,} player-weeks")

cv=collections.defaultdict(list); skew=collections.defaultdict(list)
ratios=collections.defaultdict(list)
for key,vals in series.items():
    if len(vals)<8: continue
    m=st.mean(vals)
    if m<5: continue                       # ignore non-contributors; CV explodes near zero
    s=st.pstdev(vals)
    cv[key[2]].append(s/m)
    if s>0:
        skew[key[2]].append(sum(((v-m)/s)**3 for v in vals)/len(vals))
    for v in vals: ratios[key[2]].append(v/m)

CUR={"QB":0.43,"RB":0.64,"WR":0.67,"TE":0.72}     # what the app currently assumes
out={"weekCv":{}, "skew":{}, "n":{}, "years":f"{min(SEASONS)}-{max(SEASONS)}", "ratio":{}}
print("\nWEEKLY COEFFICIENT OF VARIATION — measured vs what the app assumes")
print("  pos   measured   assumed   players   verdict")
for p in POS:
    if not cv[p]: continue
    med=st.median(cv[p]); out["weekCv"][p]=round(med,3); out["n"][p]=len(cv[p])
    sk=st.median(skew[p]) if skew[p] else 0; out["skew"][p]=round(sk,2)
    q=lambda a,x: sorted(a)[int(x*(len(a)-1))]
    out["ratio"][p]={"p15":round(q(ratios[p],.15),3),"p50":round(q(ratios[p],.50),3),
                     "p85":round(q(ratios[p],.85),3)}
    d=(med-CUR[p])/CUR[p]*100
    print(f"  {p:3}   {med:.3f}      {CUR[p]:.2f}      {len(cv[p]):4}      {d:+.0f}%")
print("\nSKEW (positive = right-tailed, which is what a lognormal assumes):")
for p in POS:
    if p in out["skew"]: print(f"  {p}: {out['skew'][p]:+.2f}   week/mean 15th-50th-85th: "
        f"{out['ratio'][p]['p15']:.2f} / {out['ratio'][p]['p50']:.2f} / {out['ratio'][p]['p85']:.2f}")
json.dump(out,open(os.path.join(HERE,"weekcv.json"),"w"),indent=1)
print("\nwrote weekcv.json")
