"""
Are the probabilities the app prints actually calibrated?

Everything downstream — win probability, playoff odds, title odds, trade deltas — is generated by
drawing a player's weekly score around his PROJECTION with a spread set by WEEK_CV. The 82 self-
tests prove that machinery is self-consistent. Nothing proved it was right. This measures it.

The subtlety that makes this worth doing: WEEK_CV was measured as a player's week-to-week spread
around his OWN SEASON MEAN. But the app draws around the PROJECTION, and the actual outcome differs
from the projection by TWO things — the projection being wrong about his true level (forecast
error), and his week-to-week noise. If the app's draw only carries the second, its distributions
are too narrow and every probability is over-confident, pushed away from 50%.

So the honest spread to draw with is the spread of (actual / projection) itself, which contains
both. This computes that, checks the app's current model against it with a probability-integral
transform (if the model is right, the actual's percentile under it is uniform), and reports the
correction.
"""
import urllib.request, json, csv, io, re, time, os, math, statistics as st, collections

HERE=os.path.dirname(os.path.abspath(__file__))
YEARS=[2021,2022,2023,2024]; POS=("QB","RB","WR","TE")
WEEK_CV={"QB":0.438,"RB":0.591,"WR":0.639,"TE":0.641}   # what the app currently draws with
def norm(n):
    n=str(n).lower(); n=re.sub(r"[.'`]","",n); n=re.sub(r"\b(jr|sr|ii|iii|iv|v)\b","",n)
    n=re.sub(r"[^a-z ]"," ",n); return re.sub(r"\s+"," ",n).strip()
def gj(u,t=90):
    r=urllib.request.Request(u,headers={"User-Agent":"Mozilla/5.0"})
    return json.loads(urllib.request.urlopen(r,timeout=t).read())
def gt(u,t=240):
    r=urllib.request.Request(u,headers={"User-Agent":"Mozilla/5.0"})
    return urllib.request.urlopen(r,timeout=t).read().decode("utf8","replace")

posq="&".join(f"position[]={p}" for p in POS)
rows=[]   # (pos, proj, actual)
for yr in YEARS:
    act={}
    raw=gt(f"https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_{yr}.csv")
    for r in csv.DictReader(io.StringIO(raw)):
        if (r.get("season_type") or "REG")!="REG" or r.get("position") not in POS: continue
        try: w=int(r["week"]); v=float(r.get("fantasy_points_ppr") or 0)
        except Exception: continue
        act[(norm(r.get("player_display_name") or ""),r["position"],w)]=v
    hit=0
    for w in range(1,18):
        try: d=gj(f"https://api.sleeper.com/projections/nfl/{yr}/{w}?season_type=regular&{posq}&order_by=pts_ppr")
        except Exception: continue
        for it in d or []:
            pl=it.get("player") or {}; p=pl.get("position")
            if p not in POS: continue
            pr=(it.get("stats") or {}).get("pts_ppr")
            if pr is None or pr<5: continue                # only startable projections
            key=(norm((pl.get("first_name","")+" "+pl.get("last_name","")).strip()),p,w)
            if key in act: rows.append((p,float(pr),act[key])); hit+=1
        time.sleep(0.12)
    print(f"  {yr}: {hit:,}")

# ---- the empirical spread of actual/projection, per position ----
def q(a,x): a=sorted(a); return a[min(len(a)-1,int(x*(len(a)-1)))]
def lognormCdf(x,cv):
    # app's weekly factor: lognormal, mean 1, so median = 1/sqrt(1+cv^2)
    if x<=0: return 0.0
    s=math.sqrt(math.log(1+cv*cv)); mu=-s*s/2
    return 0.5*(1+math.erf((math.log(x)-mu)/(s*math.sqrt(2))))

print("\nSPREAD of actual/projection (what a draw around the projection should look like):")
PRED_CV={}
for p in POS:
    r=[a/pr for (pp,pr,a) in rows if pp==p]
    m=st.mean(r); sd=st.pstdev(r)
    PRED_CV[p]=round(sd/m,3)
    print(f"  {p}: median {q(r,.5):.2f}  p15 {q(r,.15):.2f}  p85 {q(r,.85):.2f}  CV {sd/m:.3f}   (app draws with {WEEK_CV[p]:.3f})")

# ---- probability-integral transform: is the actual's percentile under the model uniform? ----
def coverage(cvmap,label):
    print(f"\nPIT coverage with {label} — fraction of actuals below each model percentile (ideal in parens):")
    print(f"  {'pos':4} p10(.10) p25(.25) p50(.50) p75(.75) p90(.90)")
    tot=collections.defaultdict(list)
    for (p,pr,a) in rows:
        u=lognormCdf(a/pr, cvmap[p])
        tot[p].append(u)
    for p in POS:
        us=tot[p]
        cov=lambda thr: sum(1 for u in us if u<=thr)/len(us)
        print(f"  {p:4} {cov(.10):.2f}     {cov(.25):.2f}     {cov(.50):.2f}     {cov(.75):.2f}     {cov(.90):.2f}")

coverage(WEEK_CV,"the app's current WEEK_CV (spread around actual mean)")
coverage(PRED_CV,"PRED_CV (spread around the projection)")

# ---- matchup calibration: synthetic lineup-vs-lineup, predicted vs realized win rate ----
print("\nMATCHUP CALIBRATION (synthetic 9-player lineups, predicted win prob vs realized):")
byWeek=collections.defaultdict(list)
for i,(p,pr,a) in enumerate(rows): byWeek[i%1000].append((p,pr,a))   # arbitrary grouping into pools
pool=[(p,pr,a) for (p,pr,a) in rows]
import random as _r
def predWin(lineA,lineB,cvmap,sims=400,rng=None):
    win=0
    for _ in range(sims):
        sa=sum(pr*_lognorm(cvmap[p],rng) for (p,pr,a) in lineA)
        sb=sum(pr*_lognorm(cvmap[p],rng) for (p,pr,a) in lineB)
        if sa>sb: win+=1
    return win/sims
def _lognorm(cv,rng):
    s=math.sqrt(math.log(1+cv*cv)); return math.exp(-s*s/2+rng.gauss(0,1)*s)
# deterministic pseudo-random using a fixed seed (harness reproducibility, not app runtime)
rng=__import__("random").Random(12345)
buckets={cv_label:collections.defaultdict(lambda:[0,0]) for cv_label in ("WEEK_CV","PRED_CV")}
N=4000
for _ in range(N):
    idx=rng.sample(range(len(pool)),18)
    lineA=[pool[i] for i in idx[:9]]; lineB=[pool[i] for i in idx[9:]]
    realA=sum(a for (p,pr,a) in lineA); realB=sum(a for (p,pr,a) in lineB)
    realWin=1 if realA>realB else 0
    for lbl,cvmap in (("WEEK_CV",WEEK_CV),("PRED_CV",PRED_CV)):
        pw=predWin(lineA,lineB,cvmap,300,rng)
        b=min(9,int(pw*10))
        buckets[lbl][b][0]+=realWin; buckets[lbl][b][1]+=1
for lbl in ("WEEK_CV","PRED_CV"):
    print(f"\n  {lbl}: predicted bucket -> realized win rate")
    for b in range(10):
        w,n=buckets[lbl][b]
        if n<30: continue
        print(f"    {b*10:2d}-{b*10+9}%  realized {w/n*100:4.1f}%  (n={n})")

json.dump({"predCv":PRED_CV,"weekCv":WEEK_CV,"years":YEARS,"n":len(rows),
           "ratioBands":{p:{"p15":round(q([a/pr for (pp,pr,a) in rows if pp==p],.15),3),
                            "p50":round(q([a/pr for (pp,pr,a) in rows if pp==p],.5),3),
                            "p85":round(q([a/pr for (pp,pr,a) in rows if pp==p],.85),3)} for p in POS}},
          open(os.path.join(HERE,"calib.json"),"w"),indent=1)
print("\nwrote calib.json")
